[package]
name = "caps"
version = "0.3.4-alpha.0"
authors = ["Luca Bruno <lucab@debian.org>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/lucab/caps-rs"
documentation = "https://docs.rs/caps"
description = "A pure-Rust library to work with Linux capabilities"
keywords = ["Linux", "capabilities", "POSIX", "getcap", "setcap"]
exclude = [
".gitignore",
".travis.yml",
]

[dependencies]
errno = "0.2"
failure = "0.1"
libc = "0.2"

[package.metadata.release]
sign-commit = true
upload-doc = false
disable-publish = true
disable-push = true
pre-release-commit-message = "cargo: caps release {{version}}"
pro-release-commit-message = "cargo: development version bump"
tag-message = "caps {{version}}"
